#liip
liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: %kernel.root_dir%/../web
                cache_prefix: media
#    cache_mkdir_mode: 0777

    loaders:
        default:
            filesystem:
                data_root: %kernel.root_dir%/../web

    driver:               gd
    cache:                default
    data_loader:          default
    default_image:        null
    controller:
        filter_action:         liip_imagine.controller:filterAction
        filter_runtime_action: liip_imagine.controller:filterRuntimeAction

    filter_sets:
        25x25:
            quality: 100
            filters:
                thumbnail: { size: [25, 25], mode: outbound }
        32x32:
            quality: 100
            filters:
                thumbnail: { size: [32, 32], mode: outbound }
        40x40:
            quality: 100
            filters:
                thumbnail: { size: [40, 40], mode: outbound }
        60x60:
            quality: 100
            filters:
                thumbnail: { size: [60, 60], mode: outbound }
        90x90:
            quality: 100
            filters:
                thumbnail: { size: [90, 90], mode: outbound }
        120x120:
            quality: 100
            filters:
                thumbnail: { size: [120, 120], mode: outbound }
        150x150:
            quality: 100
            filters:
                thumbnail: { size: [150, 150], mode: outbound }
        # Prototype
        name:
            quality:              100
            jpeg_quality:         ~
            png_compression_level:  ~
            png_compression_filter: ~
            animated:             false
            format:               ~
            cache:                ~
            data_loader:          ~
            default_image:        null
            filters:

                # Prototype
                name:                 []

            post_processors:

                # Prototype
                name:                 []
