<?php

namespace COM\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function getUsersNotSchoolAdmin($school, $query) {
		$schoolAdminRepository = $this->getEntityManager()->getRepository('COMSchoolBundle:SchoolAdmin');

        $schoolAdmins = $schoolAdminRepository->findBy(array(
            'school' => $school,
            'active' => true,
        ));
		$qb = $this->createQueryBuilder('user');
		if($schoolAdmins){
			$user_ids = array();
			foreach ($schoolAdmins as $schoolAdmin){
				array_push($user_ids, $schoolAdmin->getUser()->getId());
			}

			$qb
			->where('user.id NOT IN (:user_ids)')
			->setParameter('user_ids', $user_ids)
			->andwhere('(user.username LIKE :query) OR (user.email LIKE :query) OR (user.name LIKE :query)')
			->setParameter('query', '%'.$query.'%')
			->setMaxResults( 4 );
			;
		}else{
			$qb
			->where('(user.username LIKE :query) OR (user.email LIKE :query) OR (user.name LIKE :query)')
			->setParameter('query', '%'.$query.'%')
			->setMaxResults( 4 );
			;
		}
		
        $users = $qb->getQuery()->getResult();
		return $users;
    }
}
