<?php

namespace COM\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonimageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonimageRepository extends EntityRepository
{
}
