<?php

namespace COM\BusinessBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductimageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductimageRepository extends EntityRepository
{
}
