<?php

namespace COM\TrainingBundle\Repository;

/**
 * FeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeeRepository extends \Doctrine\ORM\EntityRepository
{
	public function getFeesByStudentgroupBetween($studentgroup, $datebegin, $dateend)
    {
        $qb = $this->createQueryBuilder('fee');

        $qb->where('fee.paymentdate <= :dateend')
		   ->setParameter('dateend', $dateend)
		   ->andWhere('fee.paymentdate >= :datebegin')
		   ->setParameter('datebegin', $datebegin)
		   ->andWhere('fee.studentgroup = :studentgroup')
		   ->setParameter('studentgroup', $studentgroup)
		   ->andWhere('fee.deleted = :deleted')
		   ->setParameter('deleted', false);

        return $qb->getQuery()->getResult();
    }
}
