<?php

namespace COM\TrainingBundle\Repository;

/**
 * StudentgroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentgroupRepository extends \Doctrine\ORM\EntityRepository
{
}
