<?php

namespace COM\StaffBundle\Repository;

/**
 * AbsenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbsenceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCurrentAbsencesByEmployee($employee)
    {
        $qb = $this->createQueryBuilder('absence');

		$now = new \DateTime();
        $qb->where('absence.datebegin < :now')
		   ->andWhere('absence.dateend > :now')
		   ->setParameter('now', $now)
		   ->andWhere('absence.employee = :employee')
		   ->setParameter('employee', $employee)
		   ->andWhere('absence.deleted = :deleted')
		   ->setParameter('deleted', false);

        return $qb->getQuery()->getResult();
    }
}
