<?php

namespace COM\BusinessBundle\Repository;

/**
 * ExpenditureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpenditureRepository extends \Doctrine\ORM\EntityRepository
{
	public function getExpendituresBetween($datebegin, $dateend)
    {
        $qb = $this->createQueryBuilder('expenditure');

        $qb->where('expenditure.date <= :dateend')
		   ->setParameter('dateend', $dateend)
		   ->andWhere('expenditure.date >= :datebegin')
		   ->setParameter('datebegin', $datebegin)
		   ->andWhere('expenditure.deleted = :deleted')
		   ->setParameter('deleted', false);

        return $qb->getQuery()->getResult();
    }
}
