<?php

namespace COM\BusinessBundle\Repository;

/**
 * GainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GainRepository extends \Doctrine\ORM\EntityRepository
{
	public function getGainsBetween($datebegin, $dateend)
    {
        $qb = $this->createQueryBuilder('gain');

        $qb->where('gain.date <= :dateend')
		   ->setParameter('dateend', $dateend)
		   ->andWhere('gain.date >= :datebegin')
		   ->setParameter('datebegin', $datebegin)
		   ->andWhere('gain.deleted = :deleted')
		   ->setParameter('deleted', false);

        return $qb->getQuery()->getResult();
    }
}
