<?php

namespace COM\BusinessBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
	//search
    public function getProductSearch($q)
    {
        $qb = $this->createQueryBuilder('product');

        $qb
        ->where('product.name LIKE :q OR product.reference LIKE :q')
        ->setParameter('q', '%'.$q.'%')
	   ->andWhere('product.deleted = :deleted')
	   ->setParameter('deleted', false);
		
		$qb
        ->orderBy('product.id', 'DESC')
        ;

        return $qb
        ->getQuery()
        ->getResult()
        ;
    }
}
