<?php

namespace COM\BusinessBundle\Repository;

/**
 * StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockRepository extends \Doctrine\ORM\EntityRepository
{
	
	public function getStocksBetween($datebegin, $dateend)
    {
        $qb = $this->createQueryBuilder('stock');

        $qb->where('stock.date <= :dateend')
		   ->setParameter('dateend', $dateend)
		   ->andWhere('stock.date >= :datebegin')
		   ->setParameter('datebegin', $datebegin)
		   ->andWhere('stock.deleted = :deleted')
		   ->setParameter('deleted', false);

        return $qb->getQuery()->getResult();
    }
}
