<?php

namespace COM\BusinessBundle\Repository;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTransactionsBetween($datebegin, $dateend)
    {
        $qb = $this->createQueryBuilder('transaction');

        $qb->where('transaction.date <= :dateend')
		   ->setParameter('dateend', $dateend)
		   ->andWhere('transaction.date >= :datebegin')
		   ->setParameter('datebegin', $datebegin)
		   ->andWhere('transaction.deleted = :deleted')
		   ->setParameter('deleted', false);

        return $qb->getQuery()->getResult();
    }
}
