<?php

namespace COM\BusinessBundle\Repository;

/**
 * TransactionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
