<?php

namespace COM\PlatformBundle\Repository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends \Doctrine\ORM\EntityRepository
{
	//search
    public function getPersonSearch($q)
    {
        $qb = $this->createQueryBuilder('person');

        $qb
        ->where('person.name LIKE :q OR person.firstname LIKE :q')
        ->setParameter('q', '%'.$q.'%');
		
		$qb
        ->orderBy('person.id', 'DESC')
        ;

        return $qb
        ->getQuery()
        ->getResult()
        ;
    }
}
