<?php

namespace COM\PlatformBundle\Repository;

/**
 * TakinglineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TakinglineRepository extends \Doctrine\ORM\EntityRepository
{
}
