<?php

namespace COM\PlatformBundle\Repository;

/**
 * TakingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TakingRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTakingsBefore($dateSeuil)
    {
        $qb = $this->createQueryBuilder('taking');

        $qb->where('taking.date < :dateSeuil')
		   ->setParameter('dateSeuil', $dateSeuil);

        return $qb->getQuery()->getResult();
    }
}
